### ISSUE TITLE
竖屏播放视频时，下方的集数显示基本上都有问题，显示不全

### ISSUE THREAD

**Issue by piapiapiapapapa** [XiaoRanLiu3119/TVBoxOS#3]

**Comment by XiaoRanLiu3119** [comment]
如是选集数量显示不全,目前已优化显示方式,简单自测后再推送。
其他问题请至少提供下手机型号/片名/截图,以便纠错

**Comment by piapiapiapapapa** [comment]
基本上百分之八九十的视频集数都显示不全，我截了部分图片，你看一下，图片上有电视剧的名称，因为我在一个群里面，好多人都说这个问题我的手机型号：红米K50![Screenshot_2023-09-02-19-44-36-062_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS/assets/105154711/57f9f8f3-d08f-4724-a906-1541dbb66076)

![Screenshot_2023-09-02-19-44-52-698_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS/assets/105154711/9f7c2d61-586b-4c25-8fbf-41f31037aec5)

![Screenshot_2023-09-02-19-42-22-102_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS/assets/105154711/bbcd422e-2c73-4a41-a097-572d32fe81f9)

![Screenshot_2023-09-02-19-47-39-915_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS/assets/105154711/5528aaf2-c90c-4a8d-9c9d-53aaa4fbf623)

![Screenshot_2023-09-02-19-46-13-868_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS/assets/105154711/ac6bead0-c6cd-4a89-9eb6-7be0d38ee3d4)

![Screenshot_2023-09-02-19-40-25-731_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS/assets/105154711/5322a0d2-187d-46c7-afcf-c5b0cdf4c885)

**Comment by XiaoRanLiu3119** [comment]
好的，了解，和其他改动一起发

**Comment by piapiapiapapapa** [comment]
好的，大佬辛苦
