### ISSUE TITLE
赞赞赞！求加入iOS端适配

### ISSUE THREAD

**Issue by 86096960** [XiaoRanLiu3119/TVBoxOS#5]
不知道是不是和猫大的编写代码一样，如果不费事的话，求大佬顺手打包个iOS端的

**Comment by piapiapiapapapa** [comment]
就算打包个ios端的壳子，没有适配的接口也是白搭，安卓接口和ios的应该是完全不一样的东西，安卓生态好，维护接口的人多，ios会没啥接口的，不知道说的对不对？欢迎大佬指正。

**Comment by XiaoRanLiu3119** [comment]
咱也不是大佬啊,做不到啊。家里ios设备用的伪装上架那种,嵌web的,对付用,找找看
